//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donHang()
        {
            this.chiTietDHs = new HashSet<chiTietDH>();
        }
    
        public int ID { get; set; }
        public int khachHang { get; set; }
        public string dcGiaoHang { get; set; }
        public int maPhuong { get; set; }
        public int maQuan { get; set; }
        public int maTP { get; set; }
        public bool xuatHD { get; set; }
        public System.DateTime ngayDatHang { get; set; }
        public Nullable<System.DateTime> ngayGiaoHang { get; set; }
        public Nullable<bool> thanhCong { get; set; }
        public string dvVanChuyen { get; set; }
        public string maVanChuyen { get; set; }
        public Nullable<int> phiShip { get; set; }
        public string ghiChuKhach { get; set; }
        public string ghiChuShop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDH> chiTietDHs { get; set; }
        public virtual PhuongXa PhuongXa { get; set; }
        public virtual QuanHuyen QuanHuyen { get; set; }
        public virtual taiKhoan taiKhoan { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
