//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class onlineTradeEntities1 : DbContext
    {
        public onlineTradeEntities1()
            : base("name=onlineTradeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anh> anhs { get; set; }
        public virtual DbSet<baiViet> baiViets { get; set; }
        public virtual DbSet<binhLuan> binhLuans { get; set; }
        public virtual DbSet<chiTietDH> chiTietDHs { get; set; }
        public virtual DbSet<donHang> donHangs { get; set; }
        public virtual DbSet<loaiSP> loaiSPs { get; set; }
        public virtual DbSet<PhuongXa> PhuongXas { get; set; }
        public virtual DbSet<QuanHuyen> QuanHuyens { get; set; }
        public virtual DbSet<sanPham> sanPhams { get; set; }
        public virtual DbSet<taiKhoan> taiKhoans { get; set; }
        public virtual DbSet<TinhThanh> TinhThanhs { get; set; }
    
        public virtual int remov_file_anh(string file)
        {
            var fileParameter = file != null ?
                new ObjectParameter("file", file) :
                new ObjectParameter("file", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("remov_file_anh", fileParameter);
        }
    
        public virtual int rename_path_anh(string tenCu, string tenMoi)
        {
            var tenCuParameter = tenCu != null ?
                new ObjectParameter("tenCu", tenCu) :
                new ObjectParameter("tenCu", typeof(string));
    
            var tenMoiParameter = tenMoi != null ?
                new ObjectParameter("tenMoi", tenMoi) :
                new ObjectParameter("tenMoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rename_path_anh", tenCuParameter, tenMoiParameter);
        }
    }
}
