//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanPham()
        {
            this.binhLuans = new HashSet<binhLuan>();
            this.chiTietDHs = new HashSet<chiTietDH>();
            this.anhs = new HashSet<anh>();
        }
    
        public int ID { get; set; }
        public Nullable<int> maLoai { get; set; }
        public string tenSP { get; set; }
        public string tenDuongDan { get; set; }
        public string tomTat { get; set; }
        public System.DateTime ngayDangSP { get; set; }
        public int giaBan { get; set; }
        public Nullable<int> giaKM { get; set; }
        public string dvt { get; set; }
        public string khuyenMai { get; set; }
        public int soLuong { get; set; }
        public Nullable<int> anhBia { get; set; }
        public string ndSanPham { get; set; }
        public Nullable<int> luotXem { get; set; }
        public Nullable<int> luotMua { get; set; }
        public bool dangSP { get; set; }
    
        public virtual anh anh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<binhLuan> binhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDH> chiTietDHs { get; set; }
        public virtual loaiSP loaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anh> anhs { get; set; }
    }
}
