//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taiKhoan()
        {
            this.binhLuans = new HashSet<binhLuan>();
            this.donHangs = new HashSet<donHang>();
        }
    
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string tenTK { get; set; }
        public string matKhau { get; set; }
        public System.DateTime ngayCap { get; set; }
        public bool gioiTinh { get; set; }
        public string SDT { get; set; }
        public string email { get; set; }
        public bool duocSD { get; set; }
        public string ghiChu { get; set; }
        public string vaiTro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<binhLuan> binhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donHang> donHangs { get; set; }
    }
}
